#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autload.php';
} elseif (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}

if (! $app = $app ?? $GLOBALS['app']) {
    try {
        $app = app();
    } catch (Exception $error) {
        unset($error);
        $app = new Ethereal\Foundation\Application;
    }
} else {
    $app = new Ethereal\Foundation\Application;
}

if (! $app->bound('docs')) {
    $app->bind(Ethereal\PHPDocs\Docs::class);
}

if (! $app->registered('docs')) {
    $app->register(new Ethereal\PHPDocs\DocumentationServiceProvider($app));
}

$app->make(Ethereal\Contract\Console\Kernel::class);

$app->make(Ethereal\PHPDocs\Docs::class)
    ->inputs(...$argv);
